import player from 'src/assets/images/player.png'
import verified from 'src/assets/images/verify.png'
export const DashboardDummyData = [
    {
        id: '1',
        avatar: { src: player, },
        user: {
            name: 'Jordan55',
            Rank: '1',
            score: "20000",
            aroma: "20000",
            xp: "20000",
            verfied: verified,
            numberOfReferral: "5",
            discordUserName: 'Jordan55',
        },
    },
    {
        id: '2',
        avatar: { src: player, },
        user: {
            name: 'Jordan55',
            Rank: '1',
            score: "20000",
            aroma: "20000",
            xp: "20000",
            verfied: verified,
            numberOfReferral: "5",
            discordUserName: 'Jordan55',
        },
    },
    {
        id: '3',
        avatar: { src: player, },
        user: {
            name: 'Jordan55',
            Rank: '1',
            score: "20000",
            aroma: "20000",
            xp: "20000",
            verfied: verified,
            numberOfReferral: "5",
            discordUserName: 'Jordan55',
        },
    },
    {
        id: '4',
        avatar: { src: player, },
        user: {
            name: 'Jordan55',
            Rank: '1',
            score: "20000",
            aroma: "20000",
            xp: "20000",
            verfied: verified,
            numberOfReferral: "5",
            discordUserName: 'Jordan55',
        },
    },
    {
        id: '5',
        avatar: { src: player, },
        user: {
            name: 'Jordan55',
            Rank: '1',
            score: "20000",
            aroma: "20000",
            xp: "20000",
            verfied: verified,
            numberOfReferral: "5",
            discordUserName: 'Jordan55',
        },
    },
    {
        avatar: { src: player, },
        user: {
            name: 'Jordan55',
            Rank: '1',
            score: "20000",
            aroma: "20000",
            xp: "20000",
            verfied: verified,
            numberOfReferral: "5",
            discordUserName: 'Jordan55',
        },
    },
]