import player from 'src/assets/images/player.png'
export const QuestionDummyData = [
    {
        id: '1',
        avatar: { src: player, },
        name: "Test",
        type: 'MC',
        description: "What is the full form of CPU?",
        optionA: "Central Process Unit",
        optionB: "Central Processing Unit",
        optionC: "Central Programming Unit",
        optionD: "Central Progressive Unit",
        answer: "B",
        difficulty: "Medium",
    },
    {
        id: '2',
        avatar: { src: player, },
        name: "Test",
        type: 'MC',
        description: "What is the full form of CPU?",
        optionA: "Central Process Unit",
        optionB: "Central Processing Unit",
        optionC: "Central Programming Unit",
        optionD: "Central Progressive Unit",
        answer: "B",
        difficulty: "Medium",
    },
    {
        id: '3',
        avatar: { src: player, },
        name: "Test",
        type: 'MC',
        description: "What is the full form of CPU?",
        optionA: "Central Process Unit",
        optionB: "Central Processing Unit",
        optionC: "Central Programming Unit",
        optionD: "Central Progressive Unit",
        answer: "B",
        difficulty: "Medium",
    },
    {
        id: '4',
        avatar: { src: player, },
        name: "Test",
        type: 'MC',
        description: "What is the full form of CPU?",
        optionA: "Central Process Unit",
        optionB: "Central Processing Unit",
        optionC: "Central Programming Unit",
        optionD: "Central Progressive Unit",
        answer: "B",
        difficulty: "Medium",
    },
    {
        id: '5',
        avatar: { src: player, },
        name: "Test",
        type: 'MC',
        description: "What is the full form of CPU?",
        optionA: "Central Process Unit",
        optionB: "Central Processing Unit",
        optionC: "Central Programming Unit",
        optionD: "Central Progressive Unit",
        answer: "B",
        difficulty: "Medium",
    },
    {
        id: '6',
        avatar: { src: player, },
        name: "Test",
        type: 'MC',
        description: "What is the full form of CPU?",
        optionA: "Central Process Unit",
        optionB: "Central Processing Unit",
        optionC: "Central Programming Unit",
        optionD: "Central Progressive Unit",
        answer: "B",
        difficulty: "Medium",
    },
]