export const QuizDummyData = [
    {
        id: '1',
        name: "Test",
        easyStart: "1",
        easyEnd: "8",
        mediumStart: "9",
        mediumEnd: "12",
        expertStart: "13",
        expertEnd: "15",
    },
    {
        id: '2',
        name: "Test",
        easyStart: "1",
        easyEnd: "8",
        mediumStart: "9",
        mediumEnd: "12",
        expertStart: "13",
        expertEnd: "15",
    },
    {
        id: '3',
        name: "Test",
        easyStart: "1",
        easyEnd: "8",
        mediumStart: "9",
        mediumEnd: "12",
        expertStart: "13",
        expertEnd: "15",
    },
    {
        id: '4',
        name: "Test",
        easyStart: "1",
        easyEnd: "8",
        mediumStart: "9",
        mediumEnd: "12",
        expertStart: "13",
        expertEnd: "15",
    },
    {
        id: '5',
        name: "Test",
        easyStart: "1",
        easyEnd: "8",
        mediumStart: "9",
        mediumEnd: "12",
        expertStart: "13",
        expertEnd: "15",
    },
    {
        id: '6',
        name: "Test",
        easyStart: "1",
        easyEnd: "8",
        mediumStart: "9",
        mediumEnd: "12",
        expertStart: "13",
        expertEnd: "15",
    },
]