export const RewardDummyData = [
    {
        id: '1',
        name: "Bitcoin",
        reward: "daily",
        firstReward: "250",
        secondReward: "220",
        thirdReward: '200',
        forthReward: "150",
        fifthReward: "100",
        afterFifthReward: "75",
    },
    {
        id: '2',
        name: "Ethereum",
        reward: "daily",
        firstReward: "250",
        secondReward: "220",
        thirdReward: '200',
        forthReward: "150",
        fifthReward: "100",
        afterFifthReward: "75",
    },
    {
        id: '3',
        name: "Tether",
        reward: "weekly",
        firstReward: "250",
        secondReward: "220",
        thirdReward: '200',
        forthReward: "150",
        fifthReward: "100",
        afterFifthReward: "75",
    },
    {
        id: '4',
        name: "BNB",
        reward: "monthly",
        firstReward: "250",
        secondReward: "220",
        thirdReward: '200',
        forthReward: "150",
        fifthReward: "100",
        afterFifthReward: "75",
    },
    {
        id: '5',
        name: "Dogecoin",
        reward: "weekly",
        firstReward: "250",
        secondReward: "220",
        thirdReward: '200',
        forthReward: "150",
        fifthReward: "100",
        afterFifthReward: "75",
    },
    {
        id: '6',
        name: "XRP",
        reward: "daily",
        firstReward: "250",
        secondReward: "220",
        thirdReward: '200',
        forthReward: "150",
        fifthReward: "100",
        afterFifthReward: "75",
    },
]